baseURL = 'https://sakisk.me/'
languageCode = 'en-us'
title = 'Sakis Kasampalis - Personal homepage'
theme = 'hugo-profile'

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/blog"
weight = 1

[params]
title = ""
description = "Unix, Emacs, functional programming"
favicon = "/images/lambda.png"
useBootstrapCDN = false
mathjax = false
animate = true

[params.font]
fontSize = "1rem"
fontWeight = 400
lineHeight = 1.5
textAlign = "left"

[params.navbar]
align = "ms-auto"
brandName = ""
disableSearch = false
enableSeparator = false

[params.navbar.stickyNavBar]
enable = true
showOnScrollUp = true

[params.navbar.menus]
disableAbout = false
disableExperience = true
disableEducation = true
disableProjects = false
disableAchievements = true
disableContact = false

[params.hero]
enable = true
intro = ""
title = "Hello world :)"
subtitle = "I am Sakis, a software architect based in the Netherlands"
content = "I'm always keen on implementing simple yet performant, scalable, and cost-efficient solutions."
image = "/images/profile.jpeg"

[params.hero.bottomImage]
enable = true

[params.hero.button]
enable = true
name = "Resume"
url = "/files/cv.pdf"
download = false
newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/faif"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/sakiskasampalis/"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-x-twitter"
url = "https://x.com/SKasampalis"

[params.about]
enable = true
title = "About"
image = "/images/rtfm.png"
content = """
The present: I am a Software Architect with ~ 11 years of professional experience as a Software Engineer. My main
qualities are the ability to work independently, critical thinking, and fitting well into a team. My current interests
are software architecture, distributed systems, and functional programming.

The past: Like many other computer fans, my first contact with computers was purely for entertaining reasons. I remember
myself playing games like Titus the Fox and Prince of Persia on the 486 of my friend. I also remember my friend trying
to show me how to move a turtle using simple commands (Logo).

Years later, my brother brought at home our first computer. An AMD Athlon Thunderbird 1 GHZ. Another friend of mine
passionate with computers (who was lucky enough to own a computer a couple of years before me) started to teach me the
basics of HTML. At the same time we were also learning about computer hardware (basically we were assembling and
disassembling our own computers to find out what's inside), the CLI of MS-DOS, and Windows programming (AFAIR Visual
Basic). Apart from the hardware and the CLI parts, I don't remember myself being extremely fascinated by the rest stuff.
And then...

One day I saw my brother playing with an unfamiliar user interface (GNOME). I asked him to give me some details. The
system was called Red Hat Linux 7.1. It was something different and I really liked the idea. I found myself reading my
brother's Red Hat books and trying to learn more and more about it. When my brother removed Red Hat because he wasn't
patient enough to learn how to use it in practice, I was extremely annoyed. I bought my own SuSE box and installed it on
the computer. That was it. From that day, I said goodbye to the Windows world. Nothing could be compared with the CLI of
GNU/Linux, shell scripting, configuring and compiling my own kernels, etc. During 2005-2015 I was using Debian GNU/Linux
as my primary system. In 2015, I decided to try something different and switched to macOS.

In the meantime, after studying the fundamentals of Electronics in a Technical High-School, I decided to switch directions
and follow an Computer Engineering related BSc education. After the BSc, the MSc followed. I believe that through the
years, some of the things that I have been taught or chose to study were (and still are) very useful and some were (and of
course still are) a bad choice. But as W. W. Sawyer once said 'If you start by trying to be perfect, you will get
nowhere. The road to perfection is by way of making mistakes'."""

[params.about.skills]
enable = true
title = "A few technologies I've been working with professionally recently:"
items = [ "AWS", "Terraform", "Quarkus", "Python" ]

[params.projects]
enable = true
title = "Portfolio"

[[params.projects.items]]
title = "Mastering Python Design Patterns"
content = """Whether you're working on user interfaces (UIs), web apps, APIs, data pipelines, or AI models, this book equips
you with the knowledge to build robust and maintainable software."""
image = "/images/projects/python-patterns-book.jpg"
badges = [ "book", "python", "design patterns", "author" ]

[params.projects.items.featured]
name = "Buy"
link = "https://www.packtpub.com/en-us/product/mastering-python-design-patterns-9781837639618"

[[params.projects.items.links]]
icon = "fab fa-github"
url = "https://github.com/PacktPublishing/Mastering-Python-Design-Patterns-Third-Edition"

[[params.projects.items]]
title = "Copy On Write Based Filesystems"
content = "I evaluate the performance and scalability of ZFS and Btrfs, and propose a transaction oriented file system call interface."
image = "/images/projects/cow-thesis.png"
badges = [ "MSc", "thesis", "copy-on-write", "filesystems" ]

[params.projects.items.featured]
name = "PDF"
link = "/files/copy-on-write-based-file-systems.pdf"

[[params.projects.items]]
title = "My GitHub repos"
content = """Check my GitHub repositories. From implementing common algorithms in different programming languages, to solving Sudoku
puzzles in Prolog, I hope that you can find something interesting there!"""
image = "/images/projects/github-logo.png"
badges = [ "GitHub", "repositories" ]

[[params.projects.items.links]]
icon = "fab fa-github"
url = "https://github.com/faif"

[[params.projects.items]]
title = "My goodreads book list"
content = """If you love reading books, your are more than welcome to check my goodreads collection. Find out which books I have read and
which books I'm planning to read. I'm always open to good recommendations."""
image = "/images/projects/goodreads.png"
badges = [ "goodreads", "books", "collection" ]

[params.projects.items.featured]
name = "List"
link = "https://www.goodreads.com/review/list/27581741-sakis?shelf=%23ALL%23"

[[params.projects.items]]
title = "Hardware prototypes"
content = """I like tinkering with hardware, although I haven't done that enough lately. If you are curious about this, take a look at my
prototyping videos."""
image = "/images/projects/RaspberryPi-logo.png"
badges = [ "microcontrollers", "prototypes", "electronics" ]

[params.projects.items.featured]
name = "Videos"
link = "https://vimeo.com/user32695250/videos/page:1/sort:date"

[params.contact]
enable = true
title = "Contact"
content = """There are different ways to reach out. In general I prefer asynchronous communication, so please use email, LinkedIn, or X (former twitter). Calling should be the last resort. You can find my email and phone number in my CV."""
btnName = "Contact me"
btnLink = "/files/cv.pdf"

[params.footer.recentPosts]
path = "blog"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = true

[params.listPages]
disableFeaturedImage = true

[params.singlePages]
socialShare = false

[params.singlePages.readTime]
enable = true
content = "min read"

[params.singlePages.scrollprogress]
enable = true

[params.singlePages.tags]
openInNewTab = true

[params.terms]
read = "Read"
toc = "Table Of Contents"
copyright = "Licensed under CC BY 4.0"
pageNotFound = "Oops, nothing found! But keep looking around..."
emailText = "Check out this site"

[params.datesFormat]
article = "Jan 2, 2006"
articleList = "Jan 2, 2006"
articleRecent = "Jan 2, 2006"
